/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;

public class Main {

    public static void main(String[] args) {
    	CLI cli = new CLI();
        String github_url = cli.CLI(args);
        if (github_url.length()==0) {
        	System.exit(0);
        }
    }
}
