/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;

import java.io.File;
import java.io.IOException;
import java.util.regex.Pattern;

import RepoMiner.CommitMiner;


public class Main {
	
    public static void main(String[] args) throws IOException {
    	CLI cli = new CLI();
        String localPath = cli.CommonCLI(args);
        CommitMiner commitmine = new CommitMiner(localPath);
    }
}
