/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;

public class Main {

    public static void main(String[] args) {
    	CLI cli = new CLI();
        String github_url = cli.CommonCLI(args);
        System.out.print(github_url);
    }
}
